service:
  extensions:
    - jaeger_query
    - jaeger_storage
  pipelines:
    traces:
      exporters:
        - jaeger_storage_exporter
      receivers:
        - otlp
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "${env:JAEGER_LISTEN_HOST:-localhost}:4317"
      http:
        endpoint: "${env:JAEGER_LISTEN_HOST:-localhost}:4318"
extensions:
  jaeger_storage:
    backends:
      trace_storage:
        memory:
          max_traces: 100000
  jaeger_query:
    storage:
      traces: trace_storage
    base_path: /
    grpc:
      endpoint: 0.0.0.0:16685
    http:
      endpoint: 0.0.0.0:16686
exporters:
  jaeger_storage_exporter:
    trace_storage: trace_storage
    queue:
      num_consumers: 10
      queue_size: 100
