services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - './data:/var/lib/grafana'
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/config.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yaml
    volumes:
      - ./promtail/config.yaml:/etc/promtail/config.yaml
      - /var/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock

  jaeger:
    image: jaegertracing/jaeger:latest
    container_name: jaeger
    restart: unless-stopped
    command: --config /etc/jaeger/config.yaml
    volumes:
      - ./jaeger/config.yaml:/etc/jaeger/config.yaml
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16685:16685"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "5778:5778"
      - "9411:9411"

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    command:
      - --disable_metrics=disk,referenced_memory
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    devices:
      - "/dev/kmsg"
    ports:
      - '8080:8080'

  true-tech-server:
    container_name: true-tech-server
    restart: unless-stopped
    build:
      context: ../test-service
      dockerfile: docker/server/Dockerfile
    ports:
      - "9080:9080"
      - "9081:9081"
      - "9082:9082"
      - "9083:9083"
    environment:
      - SERVER_ADDRESS=:9080
      - DEBUG_CONTROL_URL=:9081
      - PPROF_ADDRESS=:9082
      - PROMETHEUS_ADDRESS=:9083
      - TRACE_COLLECTOR=jaeger:4317
    deploy:
      resources:
        limits:
          memory: 10M
        reservations:
          memory: 10M

  true-tech-client:
    container_name: true-tech-client
    restart: unless-stopped
    build:
      context: ../test-service
      dockerfile: docker/client/Dockerfile
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - SERVER_ADDRESS=true-tech-server:9080
      - PPROF_ADDRESS=:9092
      - PROMETHEUS_ADDRESS=:9093
      - TRACE_COLLECTOR=jaeger:4317
      - CLIENT_INTERVAL=1s

  true-hack:
    container_name: true-hack
    restart: unless-stopped
    build:
      context: ../true-hack
      dockerfile: Dockerfile
    ports:
      - "9050:9050"
