// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamName      string                 `protobuf:"bytes,1,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	TeamMembers   []string               `protobuf:"bytes,2,rep,name=team_members,json=teamMembers,proto3" json:"team_members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTeamRequest) Reset() {
	*x = RegisterTeamRequest{}
	mi := &file_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTeamRequest) ProtoMessage() {}

func (x *RegisterTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTeamRequest.ProtoReflect.Descriptor instead.
func (*RegisterTeamRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterTeamRequest) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *RegisterTeamRequest) GetTeamMembers() []string {
	if x != nil {
		return x.TeamMembers
	}
	return nil
}

type RegisterTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTeamResponse) Reset() {
	*x = RegisterTeamResponse{}
	mi := &file_api_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTeamResponse) ProtoMessage() {}

func (x *RegisterTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTeamResponse.ProtoReflect.Descriptor instead.
func (*RegisterTeamResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterTeamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SubmitSolutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamName      string                 `protobuf:"bytes,1,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	Solution      string                 `protobuf:"bytes,2,opt,name=solution,proto3" json:"solution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitSolutionRequest) Reset() {
	*x = SubmitSolutionRequest{}
	mi := &file_api_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSolutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSolutionRequest) ProtoMessage() {}

func (x *SubmitSolutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSolutionRequest.ProtoReflect.Descriptor instead.
func (*SubmitSolutionRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitSolutionRequest) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *SubmitSolutionRequest) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

type GetLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardRequest) Reset() {
	*x = GetLeaderboardRequest{}
	mi := &file_api_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRequest) ProtoMessage() {}

func (x *GetLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{3}
}

type GetLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*TeamScore           `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardResponse) Reset() {
	*x = GetLeaderboardResponse{}
	mi := &file_api_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardResponse) ProtoMessage() {}

func (x *GetLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetLeaderboardResponse) GetScores() []*TeamScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

type TeamScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamName      string                 `protobuf:"bytes,1,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamScore) Reset() {
	*x = TeamScore{}
	mi := &file_api_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamScore) ProtoMessage() {}

func (x *TeamScore) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamScore.ProtoReflect.Descriptor instead.
func (*TeamScore) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{5}
}

func (x *TeamScore) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *TeamScore) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_api_api_proto protoreflect.FileDescriptor

const file_api_api_proto_rawDesc = "" +
	"\n" +
	"\rapi/api.proto\x1a\x1bgoogle/protobuf/empty.proto\"U\n" +
	"\x13RegisterTeamRequest\x12\x1b\n" +
	"\tteam_name\x18\x01 \x01(\tR\bteamName\x12!\n" +
	"\fteam_members\x18\x02 \x03(\tR\vteamMembers\"0\n" +
	"\x14RegisterTeamResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"P\n" +
	"\x15SubmitSolutionRequest\x12\x1b\n" +
	"\tteam_name\x18\x01 \x01(\tR\bteamName\x12\x1a\n" +
	"\bsolution\x18\x02 \x01(\tR\bsolution\"\x17\n" +
	"\x15GetLeaderboardRequest\"<\n" +
	"\x16GetLeaderboardResponse\x12\"\n" +
	"\x06scores\x18\x01 \x03(\v2\n" +
	".TeamScoreR\x06scores\">\n" +
	"\tTeamScore\x12\x1b\n" +
	"\tteam_name\x18\x01 \x01(\tR\bteamName\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score2\xde\x01\n" +
	"\x13TrueTechHackContest\x12>\n" +
	"\fRegisterTeam\x12\x14.RegisterTeamRequest\x1a\x16.google.protobuf.Empty\"\x00\x12B\n" +
	"\x0eSubmitSolution\x12\x16.SubmitSolutionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12C\n" +
	"\x0eGetLeaderboard\x12\x16.GetLeaderboardRequest\x1a\x17.GetLeaderboardResponse\"\x00B\rZ\vcontest/apib\x06proto3"

var (
	file_api_api_proto_rawDescOnce sync.Once
	file_api_api_proto_rawDescData []byte
)

func file_api_api_proto_rawDescGZIP() []byte {
	file_api_api_proto_rawDescOnce.Do(func() {
		file_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)))
	})
	return file_api_api_proto_rawDescData
}

var file_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_api_proto_goTypes = []any{
	(*RegisterTeamRequest)(nil),    // 0: RegisterTeamRequest
	(*RegisterTeamResponse)(nil),   // 1: RegisterTeamResponse
	(*SubmitSolutionRequest)(nil),  // 2: SubmitSolutionRequest
	(*GetLeaderboardRequest)(nil),  // 3: GetLeaderboardRequest
	(*GetLeaderboardResponse)(nil), // 4: GetLeaderboardResponse
	(*TeamScore)(nil),              // 5: TeamScore
	(*emptypb.Empty)(nil),          // 6: google.protobuf.Empty
}
var file_api_api_proto_depIdxs = []int32{
	5, // 0: GetLeaderboardResponse.scores:type_name -> TeamScore
	0, // 1: TrueTechHackContest.RegisterTeam:input_type -> RegisterTeamRequest
	2, // 2: TrueTechHackContest.SubmitSolution:input_type -> SubmitSolutionRequest
	3, // 3: TrueTechHackContest.GetLeaderboard:input_type -> GetLeaderboardRequest
	6, // 4: TrueTechHackContest.RegisterTeam:output_type -> google.protobuf.Empty
	6, // 5: TrueTechHackContest.SubmitSolution:output_type -> google.protobuf.Empty
	4, // 6: TrueTechHackContest.GetLeaderboard:output_type -> GetLeaderboardResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_api_proto_init() }
func file_api_api_proto_init() {
	if File_api_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_api_proto_goTypes,
		DependencyIndexes: file_api_api_proto_depIdxs,
		MessageInfos:      file_api_api_proto_msgTypes,
	}.Build()
	File_api_api_proto = out.File
	file_api_api_proto_goTypes = nil
	file_api_api_proto_depIdxs = nil
}
