global:
  scrape_interval: 15s

scrape_configs:
#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['localhost:9090']
#  - job_name: 'loki'
#    static_configs:
#      - targets: ['loki:3100']
#  - job_name: 'jaeger-all-in-one'
#    static_configs:
#      - targets: ['jaeger:14269']
  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]
  - job_name: 'true-tech-server'
    static_configs:
      - targets: [ 'true-tech-server:9083' ]
  - job_name: 'true-tech-client'
    static_configs:
      - targets: [ 'true-tech-client:9093' ]